### ISSUE TITLE
ini kenapa ya om?

### ISSUE THREAD

**Issue by rayfajars** [azharimm/football-standings-api#1]
![cors2](https://user-images.githubusercontent.com/58242304/103448734-3de10e00-4cd0-11eb-837b-518cfb72f6d6.JPG)
![cors](https://user-images.githubusercontent.com/58242304/103448735-3faad180-4cd0-11eb-9801-96429305ce6a.JPG)

**Comment by azharimm** [comment]
Kena cors itu om, coba pake proxy.
https://github.com/azharimm/cors-anywhere.
Atau proxy lain juga bisa.

**Comment by rayfajars** [comment]
okeey terima kasih om 👍
