### ISSUE TITLE
API not working anymore

### ISSUE THREAD

**Issue by angelo-savioti** [azharimm/football-standings-api#5]
I've been using the API for the last few months, but in the last weeks it stopped working. This is the response I get from Postman:

![image](https://user-images.githubusercontent.com/83730859/191838085-ab043ce3-3059-4758-aff7-3033fe850f28.png)

**Comment by atmakarimang** [comment]
Url link has change from https://api-football-standings.azharimm.site/ to https://api-football-standings.azharimm.dev/

**Comment by angelo-savioti** [comment]
Thank you for the quick response!
